language: c

git:
    depth: false

compiler:
    - gcc
    - clang

services:
    - docker

stages:
   - build

notifications:
  email:
    on_success: never
    on_failure: always

before_script:
  - ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts

jobs:
  include :
      - stage: build
        name: "Build"
        install:
          - docker pull epitechcontent/epitest-docker
        script:
          - docker run -v $PWD:/project epitechcontent/epitest-docker bash -c "cd project && make re"

script:
  - make tests_run