language: c

git:
    depth: false

compiler:
    - gcc
    - clang

services:
    - docker

stages:
   - build
   - deploy

notifications:
  email:
    on_success: never
    on_failure: always

before_script:
  - ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts

jobs:
  include :
      - stage: build
        name: "Build"
        install:
          - docker pull epitechcontent/epitest-docker
        script:
          - docker run -v $PWD:/project epitechcontent/epitest-docker bash -c "cd project && make re"

      - stage: deploy
        name: "Deployement Epitech Server"
        if: branch IN (master, travis) AND type != cron AND type != pull_request
        before_script:
          - ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts
          - git checkout $TRAVIS_BRANCH
        script:
          - git push --repo=git@git.epitech.eu:/joseph.vidal@epitech.eu/PSU_strace_2019 --force

script:
  - make tests_run